### ISSUE TITLE
layout is bad on mobile

### ISSUE THREAD

**Issue by jtligon** [cri-o/cri-o.io#13]
![img_4754](https://user-images.githubusercontent.com/428483/28283233-22860f1c-6afb-11e7-80be-f81bf637980a.PNG)

Is this a css problem or a jekyll template problem?

reported by @mrunalp

**Comment by mrunalp** [comment]
We could go over http://themes.jekyllrc.org/ and pick one that looks good everywhere.

**Comment by jtligon** [comment]
the cayman theme came from there, so lets be sure that its actually responsive.
