### ISSUE TITLE
https:// not allowed to website

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [cri-o/cri-o.io#26]
You can't do https://cri-o.io and should be able to you.  Currently the site only allows for http access.  There's a button to click somewhere in GitHub settings for the project, but I don't have access to it.

**Comment by runcom** [comment]
cri-o.io domain owner should point cri-o A records to GitHub Let's Encrypt enabled IPs. Right now that's not the case and before clicking that "enable https" button (which is greyed out right now) we need to fix DNS entries.
@aweiteka is on it.

**Comment by runcom** [comment]
the A records we need for cri-o.io are:
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
those are https enabled IPs from github. Once that's done, we can go ahead and enable https in github pages

**Comment by aweiteka** [comment]
DNS has been updated. Once this populates I'll enable HTTPS in GH pages setting.

**Comment by runcom** [comment]
> Once this populates I'll enable HTTPS in GH pages setting.

awesome, I guess all we need to do there is to disable/re-enable gh pages for the change to be effective

**Comment by aweiteka** [comment]
Done. DNS 'A' records updated.

**Comment by TomSweeneyRedHat** [comment]
Excellent!  TYVM @aweiteka and @runcom!
