### ISSUE TITLE
home page points to a non-existent systemd drop-in for kubeadm

### ISSUE THREAD

**Issue by jasonbrooks** [cri-o/cri-o.io#29]
https://kubernetes.io/docs/reference/generated/kubeadm/#kubelet-drop-in

**Comment by haircommander** [comment]
waiting on https://github.com/cri-o/cri-o/pull/2224 to land and then I'll link to that tutorial. It's not quite as easy as the one line anymore

**Comment by haircommander** [comment]
Closing per #31
